/* File produced with RAWTEX Gimp plugin v1.06
   Written by Franck Charlet. */

#define TERRAINHEIGHTMAP_TEXTURE_WIDTH 256
#define TERRAINHEIGHTMAP_TEXTURE_REAL_WIDTH 250
#define TERRAINHEIGHTMAP_TEXTURE_HEIGHT 256
#define TERRAINHEIGHTMAP_TEXTURE_REAL_HEIGHT 250
#define TERRAINHEIGHTMAP_TEXTURE_FORMAT 5
#define TERRAINHEIGHTMAP_TEXTURE_MIPMAPS 0
#define TERRAINHEIGHTMAP_TEXTURE_SWIZZLE 0

#define TERRAINHEIGHTMAP_PALETTE_FORMAT 3
#define TERRAINHEIGHTMAP_PALETTE_COLORS (228 / 8)
#define TERRAINHEIGHTMAP_PALETTE_MASK 0xff
#define TERRAINHEIGHTMAP_MIPMAPS_OFFSET0 0
